DROP TABLE IF EXISTS CONCEPT;
CREATE TABLE CONCEPT (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  CONCEPT_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  DEFINITION_STATUS_ID char(18) NOT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_CONCEPT_CONCEPT (CONCEPT_ID),
  KEY IDX_CONCEPT_CONCEPT_ETIME (CONCEPT_ID, EFFECTIVE_TIME),
  KEY IDX_CONCEPT_ETIME (EFFECTIVE_TIME),
  KEY IDX_CONCEPT_DS_ID (DEFINITION_STATUS_ID),
  KEY IDX_CONCEPT_MOD_ID (MODULE_ID),
  KEY IDX_CONCEPT_ACT (ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DESCRIPTION;
CREATE TABLE DESCRIPTION (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  DESCRIPTION_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  CONCEPT_ID varchar(18) NOT NULL,
  LANGUAGE_CODE char(2) NOT NULL,
  TYPE_ID char(18) NOT NULL,
  TERM varchar(255) NOT NULL,
  CASE_SIGNIFICANCE_ID char(18) NOT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_DESCRIPTION_C_ID_T_ID_ETIME (CONCEPT_ID, TYPE_ID, EFFECTIVE_TIME),
  KEY IDX_DESCRIPTION_T_ID_ETIME (TYPE_ID, EFFECTIVE_TIME),
  KEY IDX_DESCRIPTION_C_ID (CONCEPT_ID),
  KEY IDX_DESCRIPTION_C_ID_ETIME (CONCEPT_ID, EFFECTIVE_TIME),
  KEY IDX_DESCRIPTION_D_ID (DESCRIPTION_ID),
  KEY IDX_DESCRIPTION_ETIME (EFFECTIVE_TIME),
  KEY IDX_DESCRIPTION_ACTIVE (ACTIVE),
  KEY IDX_DESCRIPTION_M_ID (MODULE_ID),
  KEY IDX_DESCRIPTION_L_CODE (LANGUAGE_CODE),
  KEY IDX_DESCRIPTION_T_ID (TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DESCRIPTION_TP;
CREATE TABLE DESCRIPTION_TP (
  SEQ int(11) NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  DESCRIPTION_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL COMMENT '유효일자',
  ACTIVE tinyint(1) NOT NULL COMMENT '활성화 여부',
  MODULE_ID varchar(18) NOT NULL,
  CONCEPT_ID varchar(18) NOT NULL,
  LANGUAGE_CODE char(2) NOT NULL COMMENT 'ISO639',
  LANGUAGE_CULTURE char(5) DEFAULT NULL COMMENT 'ISO639 + ISO3166',
  TYPE_ID varchar(18) NOT NULL COMMENT '용어의 형태를 나타내는 식별자\n900000000000003001:Fully specified name\n900000000000548007:Preferred\n900000000000013009:Synonym\n900000000000550004:Definition',
  TERM varchar(255) NOT NULL COMMENT '용어',
  CASE_SIGNIFICANCE_ID varchar(18) NOT NULL COMMENT '대소문자 구분 민감정도를 나타내는 식별자\n900000000000448009:Entire term case insensitive\n900000000000017005:Entire term case sensitive\n900000000000020002:Only initial character case insensitive',
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP  TABLE IF EXISTS INFERRED_RELATIONSHIP;
CREATE TABLE INFERRED_RELATIONSHIP (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  RELATIONSHIP_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  SOURCE_ID varchar(18) NOT NULL,
  DESTINATION_ID varchar(18) NOT NULL,
  RELATIONSHIP_GROUP int(11) NOT NULL,
  TYPE_ID varchar(18) NOT NULL,
  CHARACTERISTIC_TYPE_ID char(18) NOT NULL,
  MODIFIER_ID varchar(18) NOT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_INFERRED_S_ID (SOURCE_ID),
  KEY IDX_INFERRED_ETIME_S_ID (EFFECTIVE_TIME, SOURCE_ID),
  KEY IDX_INFERRED__S_ID_ETIME (SOURCE_ID, EFFECTIVE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS INFERRED_RELATIONSHIP_SNAP;
CREATE TABLE INFERRED_RELATIONSHIP_SNAP (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  RELATIONSHIP_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  SOURCE_ID varchar(18) NOT NULL,
  DESTINATION_ID varchar(18) NOT NULL,
  RELATIONSHIP_GROUP int(11) NOT NULL,
  TYPE_ID varchar(18) NOT NULL,
  CHARACTERISTIC_TYPE_ID char(18) NOT NULL,
  MODIFIER_ID varchar(18) NOT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_INFERRED_S_ID (SOURCE_ID),
  KEY IDX_INFERRED_ETIME_S_ID (EFFECTIVE_TIME, SOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS STATED_RELATIONSHIP;
CREATE TABLE STATED_RELATIONSHIP (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  RELATIONSHIP_ID varchar(18) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  SOURCE_ID varchar(18) NOT NULL,
  DESTINATION_ID varchar(18) NOT NULL,
  RELATIONSHIP_GROUP int(11) NOT NULL,
  TYPE_ID varchar(18) NOT NULL,
  CHARACTERISTIC_TYPE_ID char(18) NOT NULL,
  MODIFIER_ID varchar(18) NOT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_STATED_S_ID (SOURCE_ID),
  KEY IDX_STATED_ETIME_S_ID (EFFECTIVE_TIME, SOURCE_ID),
  KEY IDX_STATED_S_ID_ETIME (SOURCE_ID, EFFECTIVE_TIME)
#) ENGINE=InnoDB AUTO_INCREMENT=1356278 DEFAULT CHARSET=utf8;
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#DROP  TABLE IF EXISTS CONCRETE_VALUES
#CREATE TABLE CONCRETE_VALUES (
#  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
#  RELATIONSHIP_ID varchar(18) NOT NULL,
#  EFFECTIVE_TIME char(8) NOT NULL,
#  ACTIVE tinyint(1) NOT NULL,
#  MODULE_ID varchar(18) NOT NULL,
#  SOURCE_ID varchar(18) NOT NULL,
#  VALUE varchar(18) NOT NULL,
#  RELATIONSHIP_GROUP int(11) NOT NULL,
#  TYPE_ID varchar(18) NOT NULL,
#  CHARACTERISTIC_TYPE_ID char(18) NOT NULL,
#  MODIFIER_ID varchar(18) NOT NULL,
#  PRIMARY KEY (SEQ),
#  KEY IDX_CONCRETE_S_ID (SOURCE_ID),
#  KEY IDX_CONCRETE_S_ETIME_S_ID (EFFECTIVE_TIME, SOURCE_ID),
#  KEY IDX_CONCRETE_S_ID_ETIME (SOURCE_ID, EFFECTIVE_TIME)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS MRCM_CONSTRAINTS;
CREATE TABLE MRCM_CONSTRAINTS (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  ATTRIBUTE_ID varchar(18) DEFAULT NULL,
  ATTRIBUTE_NAME varchar(255) DEFAULT NULL,
  SOURCE_ID varchar(18) DEFAULT NULL,
  SOURCE_NAME varchar(255) DEFAULT NULL,
  VALUE_ID varchar(18) DEFAULT NULL,
  VALUE_NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_MRCM_S_ID (SOURCE_ID),
  KEY IDX_MRCM_A_ID (ATTRIBUTE_ID),
  KEY IDX_MRCM_V_ID (VALUE_ID),
  KEY IDX_MRCM_S_ID_A_ID (SOURCE_ID, ATTRIBUTE_ID),
  KEY IDX_MRCM_A_ID_V_ID (ATTRIBUTE_ID, VALUE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS REFERENCESET;
CREATE TABLE REFERENCESET (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  REFERENCESET_ID char(36) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  REFSET_ID varchar(18) NOT NULL,
  REFERENCED_COMPONENT_ID varchar(18) NOT NULL,
  FIELD1 varchar(2047) DEFAULT NULL,
  FIELD2 varchar(550) DEFAULT NULL,
  FIELD3 varchar(255) DEFAULT NULL,
  FIELD4 varchar(399) DEFAULT NULL,
  FIELD5 varchar(6200) DEFAULT NULL,
  FIELD6 varchar(6200) DEFAULT NULL,
  FIELD7 varchar(35) DEFAULT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  UNIQUE KEY UUID (REFERENCESET_ID),
  KEY IDX_REFERENCESET_ETIME_R_ID (EFFECTIVE_TIME, REFERENCESET_ID),
  KEY IDX_REFERENCESET_R_ID_R_C_ID (REFSET_ID, REFERENCED_COMPONENT_ID),
  KEY IDX_REFERENCESET_R_ID_R_C_ID_ETIME (REFSET_ID, REFERENCED_COMPONENT_ID, EFFECTIVE_TIME),
  KEY IDX_REFERENCESET_R_C_ID_R_ID_ETIME (REFERENCED_COMPONENT_ID,REFSET_ID,EFFECTIVE_TIME) #,
  #KEY IDX_REFERENCESET_RRFAE (REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, ACTIVE, EFFECTIVE_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS USER_REFERENCESET;
CREATE TABLE USER_REFERENCESET (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  REFERENCESET_ID char(36) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  ACTIVE tinyint(1) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  REFSET_ID varchar(18) NOT NULL,
  REFERENCED_COMPONENT_ID varchar(18) NOT NULL,
  FIELD1 varchar(511) DEFAULT NULL,
  FIELD2 varchar(255) DEFAULT NULL,
  FIELD3 varchar(255) DEFAULT NULL,
  FIELD4 varchar(255) DEFAULT NULL,
  FIELD5 varchar(255) DEFAULT NULL,
  FIELD6 varchar(255) DEFAULT NULL,
  FIELD7 varchar(255) DEFAULT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  INCLUDE_SUBTYPES tinyint(1) DEFAULT NULL,
  CONCEPT_ID varchar(18) DEFAULT NULL,
  TYPE varchar(45) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# Concept/Description Editor 사용시에만 필요
DROP  TABLE IF EXISTS SCTID;
CREATE TABLE SCTID (
  SEQ int(8) NOT NULL AUTO_INCREMENT COMMENT 'SNOMED CT ID 발급 과정에서 Extension item identifier로 사용',
  CPNT_TYPE int(11) NOT NULL COMMENT 'SCTID Partition Identifier\nConcept: 0\nDescription: 1\nRelationship 2',
  CREATE_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS SCHEME;
CREATE TABLE SCHEME (
  ID varchar(45) NOT NULL,
  NAME varchar(45) NOT NULL,
  EDITION varchar(45) NOT NULL,
  VERSION varchar(10) NOT  NULL,
  AUTHORITY varchar(45) NOT NULL,
  DATE varchar(10) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


# for Index

#ALTER TABLE term.DESCRIPTION
#ADD INDEX IDX_DESCRIPTION USING BTREE (CONCEPT_ID,TERM,DESCRIPTION_ID,ACTIVE,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDX_DESCID USING BTREE (DESCRIPTION_ID)  COMMENT '',
#ADD INDEX IDX_DESMIX USING BTREE (ACTIVE,CONCEPT_ID,EFFECTIVE_TIME,TYPE_ID)  COMMENT '',
#ADD INDEX IDX_DESMIX2 USING BTREE (DESCRIPTION_ID,ACTIVE,EFFECTIVE_TIME,TYPE_ID)  COMMENT '',
#ADD INDEX IDS_DESTERM USING BTREE (ACTIVE,CONCEPT_ID,EFFECTIVE_TIME,LANGUAGE_CODE,TYPE_ID)  COMMENT '',
#ADD INDEX IDX_GET_TERM_BY_CONCEPT_ID USING BTREE (CONCEPT_ID,LANGUAGE_CODE,TYPE_ID,EFFECTIVE_TIME)  COMMENT '';

#ALTER TABLE term.DESCRIPTION_TP
#ADD INDEX IDX_DESC_IDET USING BTREE (DESCRIPTION_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDX_DESC_MXET USING BTREE (TYPE_ID,LANGUAGE_CODE,EFFECTIVE_TIME,DESCRIPTION_ID)  COMMENT '',
#ADD INDEX IDX_DESC_MIX0 USING BTREE (DESCRIPTION_ID,EFFECTIVE_TIME,ACTIVE,CONCEPT_ID)  COMMENT '',
#ADD INDEX IDX_DESC_DETL USING BTREE (DESCRIPTION_ID,EFFECTIVE_TIME,TYPE_ID,LANGUAGE_CODE)  COMMENT '',
#ADD INDEX IDX_DESC_C USING BTREE (CONCEPT_ID)  COMMENT '';

#ALTER TABLE term.INFERRED_RELATIONSHIP
#ADD INDEX IDX_INFERRED_RELATIONSHIP USING BTREE (SOURCE_ID,DESTINATION_ID)  COMMENT '',
#ADD INDEX IDX_STATED_SOURCE USING BTREE (SOURCE_ID)  COMMENT '',
#ADD INDEX IDX_INF_ISA USING BTREE (EFFECTIVE_TIME,SOURCE_ID,RELATIONSHIP_ID)  COMMENT '',
#ADD INDEX IDX_INF_SNAP USING BTREE (RELATIONSHIP_ID,TYPE_ID,SOURCE_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDX_INF_SSNAP USING BTREE (RELATIONSHIP_ID,SOURCE_ID,EFFECTIVE_TIME,ACTIVE)  COMMENT '',
#ADD INDEX IDX_INF_ESR USING BTREE (EFFECTIVE_TIME,SOURCE_ID,RELATIONSHIP_ID)  COMMENT '';

#ALTER TABLE term.STATED_RELATIONSHIP
#ADD INDEX IDX_INFERRED_RELATIONSHIP USING BTREE (SOURCE_ID,DESTINATION_ID)  COMMENT '',
#ADD INDEX IDX_STATED_SOURCE USING BTREE (SOURCE_ID)  COMMENT '';

#ALTER TABLE term.MRCM_CONSTRAINTS
#ADD INDEX IDX_SOURCE_ID USING BTREE (SOURCE_ID)  COMMENT '';

#ALTER TABLE term.REFERENCESET
#ADD INDEX IDX_REFERENCESET USING BTREE (REFSET_ID,REFERENCED_COMPONENT_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDEX_REFSET_REFCOMID USING BTREE (REFERENCED_COMPONENT_ID,REFSET_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDX_ID_COMP USING BTREE (REFSET_ID,REFERENCED_COMPONENT_ID)  COMMENT '',
#ADD INDEX IDX_SNAPSHOT USING BTREE (ACTIVE,EFFECTIVE_TIME,REFERENCESET_ID)  COMMENT '';

#ALTER TABLE term.USER_REFERENCESET
#ADD INDEX IDX_SNAPSHOT USING BTREE (ACTIVE,EFFECTIVE_TIME,REFERENCED_COMPONENT_ID,REFERENCESET_ID)  COMMENT '',
#ADD INDEX IDX_REFERENCESET USING BTREE (REFSET_ID,REFERENCED_COMPONENT_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDEX_REFSET_REFCOMID USING BTREE (REFERENCED_COMPONENT_ID,REFSET_ID,EFFECTIVE_TIME)  COMMENT '',
#ADD INDEX IDX_ID_COMP USING BTREE (REFSET_ID,REFERENCED_COMPONENT_ID)  COMMENT '';

#ALTER TABLE term.TC
#ADD INDEX IDX_GET_CHILDREN USING BTREE (PARENT_ID,CONCEPT_ID)  COMMENT '',
#ADD INDEX IDX_CPT USING BTREE (CONCEPT_ID)  COMMENT '',
#ADD INDEX IDX_PATH USING BTREE (PATH,CONCEPT_ID)  COMMENT '';
