-- =============================================================================
-- SNOMED CT / Terminology API - PostgreSQL DDL
-- 변환 출처: MySQLDDL.sql (MySQL InnoDB) → PostgreSQL 18 호환
--
-- 주요 변환 규칙:
--   bigint(20) AUTO_INCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY
--   int(11) AUTO_INCREMENT    → INTEGER GENERATED BY DEFAULT AS IDENTITY
--   tinyint(1/4)              → SMALLINT  (MySQL 1-byte boolean 대체)
--   int(11)                   → INTEGER
--   datetime                  → TIMESTAMP
--   ENGINE=InnoDB CHARSET=utf8 → 제거
--   KEY idx (col)             → 테이블 정의 분리 후 CREATE INDEX
--   UNIQUE KEY                → UNIQUE 제약 또는 CREATE UNIQUE INDEX
--   # 주석                    → -- 주석
-- =============================================================================

-- 스키마 초기화: 기존 term 스키마 전체 삭제 후 재생성
DROP SCHEMA IF EXISTS term CASCADE;
CREATE SCHEMA term;
SET search_path TO term;

-- -----------------------------------------------------------------------------
-- CONCEPT
-- SNOMED CT 개념의 전체 이력(Full release) 저장 테이블
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS CONCEPT;
CREATE TABLE CONCEPT (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONCEPT_ID        VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    -- MySQL tinyint(1) active 플래그를 SMALLINT로 매핑 (0=비활성, 1=활성)
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    DEFINITION_STATUS_ID CHAR(18)  NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_CONCEPT_CONCEPT         ON CONCEPT (CONCEPT_ID);
CREATE INDEX IDX_CONCEPT_CONCEPT_ETIME   ON CONCEPT (CONCEPT_ID, EFFECTIVE_TIME);
CREATE INDEX IDX_CONCEPT_ETIME           ON CONCEPT (EFFECTIVE_TIME);
CREATE INDEX IDX_CONCEPT_DS_ID           ON CONCEPT (DEFINITION_STATUS_ID);
CREATE INDEX IDX_CONCEPT_MOD_ID          ON CONCEPT (MODULE_ID);
CREATE INDEX IDX_CONCEPT_ACT             ON CONCEPT (ACTIVE);

-- -----------------------------------------------------------------------------
-- DESCRIPTION
-- 영어 기반 전체 이력 설명(Description) 저장 테이블
-- 국제 RF2 Full release의 sct2_Description_Full-en 파일을 적재
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS DESCRIPTION;
CREATE TABLE DESCRIPTION (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION_ID    VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    CONCEPT_ID        VARCHAR(18)  NOT NULL,
    LANGUAGE_CODE     CHAR(2)      NOT NULL,
    TYPE_ID           CHAR(18)     NOT NULL,
    TERM              VARCHAR(4096) NOT NULL,
    CASE_SIGNIFICANCE_ID CHAR(18)  NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_DESCRIPTION_C_ID_T_ID_ETIME ON DESCRIPTION (CONCEPT_ID, TYPE_ID, EFFECTIVE_TIME);
CREATE INDEX IDX_DESCRIPTION_T_ID_ETIME      ON DESCRIPTION (TYPE_ID, EFFECTIVE_TIME);
CREATE INDEX IDX_DESCRIPTION_C_ID            ON DESCRIPTION (CONCEPT_ID);
CREATE INDEX IDX_DESCRIPTION_C_ID_ETIME      ON DESCRIPTION (CONCEPT_ID, EFFECTIVE_TIME);
CREATE INDEX IDX_DESCRIPTION_D_ID            ON DESCRIPTION (DESCRIPTION_ID);
CREATE INDEX IDX_DESCRIPTION_ETIME           ON DESCRIPTION (EFFECTIVE_TIME);
CREATE INDEX IDX_DESCRIPTION_ACTIVE          ON DESCRIPTION (ACTIVE);
CREATE INDEX IDX_DESCRIPTION_M_ID            ON DESCRIPTION (MODULE_ID);
CREATE INDEX IDX_DESCRIPTION_L_CODE          ON DESCRIPTION (LANGUAGE_CODE);
CREATE INDEX IDX_DESCRIPTION_T_ID            ON DESCRIPTION (TYPE_ID);

-- -----------------------------------------------------------------------------
-- DESCRIPTION_TP
-- 다국어(Translation Package) 설명 저장 테이블
-- LANGUAGE_CULTURE 컬럼으로 국가별 언어팩 구분 (예: ko-KR, en-US)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS DESCRIPTION_TP;
CREATE TABLE DESCRIPTION_TP (
    -- int(11) AUTO_INCREMENT: 국제 설명 수가 bigint 불필요 수준이므로 INTEGER 사용
    SEQ               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION_ID    VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    CONCEPT_ID        VARCHAR(18)  NOT NULL,
    LANGUAGE_CODE     CHAR(2)      NOT NULL,
    LANGUAGE_CULTURE  CHAR(5)      DEFAULT NULL,
    -- TYPE_ID: 900000000000003001=FSN, 900000000000548007=Preferred, 900000000000013009=Synonym
    TYPE_ID           VARCHAR(18)  NOT NULL,
    TERM              VARCHAR(4096) NOT NULL,
    -- CASE_SIGNIFICANCE_ID: 900000000000448009=CI, 900000000000017005=CS, 900000000000020002=Initial-CI
    CASE_SIGNIFICANCE_ID VARCHAR(18) NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

-- -----------------------------------------------------------------------------
-- INFERRED_RELATIONSHIP
-- IS-A 및 속성 관계의 전체 이력(Full release) 저장 테이블
-- Classifier가 추론(infer)한 관계만 포함
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS INFERRED_RELATIONSHIP;
CREATE TABLE INFERRED_RELATIONSHIP (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    RELATIONSHIP_ID   VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    SOURCE_ID         VARCHAR(18)  NOT NULL,
    DESTINATION_ID    VARCHAR(18)  NOT NULL,
    RELATIONSHIP_GROUP INTEGER     NOT NULL,
    TYPE_ID           VARCHAR(18)  NOT NULL,
    CHARACTERISTIC_TYPE_ID CHAR(18) NOT NULL,
    MODIFIER_ID       VARCHAR(18)  NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_INFERRED_S_ID         ON INFERRED_RELATIONSHIP (SOURCE_ID);
CREATE INDEX IDX_INFERRED_ETIME_S_ID   ON INFERRED_RELATIONSHIP (EFFECTIVE_TIME, SOURCE_ID);
CREATE INDEX IDX_INFERRED__S_ID_ETIME  ON INFERRED_RELATIONSHIP (SOURCE_ID, EFFECTIVE_TIME);

-- -----------------------------------------------------------------------------
-- INFERRED_RELATIONSHIP_SNAP
-- IS-A 및 속성 관계의 스냅샷(Snapshot release) 저장 테이블
-- 최신 상태의 관계만 보관하여 빠른 조회에 사용
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS INFERRED_RELATIONSHIP_SNAP;
CREATE TABLE INFERRED_RELATIONSHIP_SNAP (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    RELATIONSHIP_ID   VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    SOURCE_ID         VARCHAR(18)  NOT NULL,
    DESTINATION_ID    VARCHAR(18)  NOT NULL,
    RELATIONSHIP_GROUP INTEGER     NOT NULL,
    TYPE_ID           VARCHAR(18)  NOT NULL,
    CHARACTERISTIC_TYPE_ID CHAR(18) NOT NULL,
    MODIFIER_ID       VARCHAR(18)  NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_INFERRED_SNAP_S_ID        ON INFERRED_RELATIONSHIP_SNAP (SOURCE_ID);
CREATE INDEX IDX_INFERRED_SNAP_ETIME_S_ID  ON INFERRED_RELATIONSHIP_SNAP (EFFECTIVE_TIME, SOURCE_ID);

-- -----------------------------------------------------------------------------
-- STATED_RELATIONSHIP
-- 저자가 명시적으로 작성한 관계의 전체 이력 저장 테이블
-- Classifier 추론 전 원본 관계(IS-A, attribute) 포함
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS STATED_RELATIONSHIP;
CREATE TABLE STATED_RELATIONSHIP (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    RELATIONSHIP_ID   VARCHAR(18)  NOT NULL,
    EFFECTIVE_TIME    CHAR(8)      NOT NULL,
    ACTIVE            SMALLINT     NOT NULL,
    MODULE_ID         VARCHAR(18)  NOT NULL,
    SOURCE_ID         VARCHAR(18)  NOT NULL,
    DESTINATION_ID    VARCHAR(18)  NOT NULL,
    RELATIONSHIP_GROUP INTEGER     NOT NULL,
    TYPE_ID           VARCHAR(18)  NOT NULL,
    CHARACTERISTIC_TYPE_ID CHAR(18) NOT NULL,
    MODIFIER_ID       VARCHAR(18)  NOT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_STATED_S_ID         ON STATED_RELATIONSHIP (SOURCE_ID);
CREATE INDEX IDX_STATED_ETIME_S_ID   ON STATED_RELATIONSHIP (EFFECTIVE_TIME, SOURCE_ID);
CREATE INDEX IDX_STATED_S_ID_ETIME   ON STATED_RELATIONSHIP (SOURCE_ID, EFFECTIVE_TIME);

-- -----------------------------------------------------------------------------
-- MRCM_CONSTRAINTS
-- SNOMED CT Machine Readable Concept Model(MRCM) 속성 도메인/범위 제약 조건
-- REFERENCESET에서 파생한 비정규화 조회용 테이블 (importer 전처리 결과)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS MRCM_CONSTRAINTS;
CREATE TABLE MRCM_CONSTRAINTS (
    SEQ            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ATTRIBUTE_ID   VARCHAR(18)  DEFAULT NULL,
    ATTRIBUTE_NAME VARCHAR(255) DEFAULT NULL,
    SOURCE_ID      VARCHAR(18)  DEFAULT NULL,
    SOURCE_NAME    VARCHAR(255) DEFAULT NULL,
    VALUE_ID       VARCHAR(18)  DEFAULT NULL,
    VALUE_NAME     VARCHAR(255) DEFAULT NULL,
    -- MRCM Attribute Range Snapshot의 attributeRule에서 추출한 카디널리티 (예: 0..*, 0..1)
    CARDINALITY    VARCHAR(20)  DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_MRCM_S_ID      ON MRCM_CONSTRAINTS (SOURCE_ID);
CREATE INDEX IDX_MRCM_A_ID      ON MRCM_CONSTRAINTS (ATTRIBUTE_ID);
CREATE INDEX IDX_MRCM_V_ID      ON MRCM_CONSTRAINTS (VALUE_ID);
CREATE INDEX IDX_MRCM_S_ID_A_ID ON MRCM_CONSTRAINTS (SOURCE_ID, ATTRIBUTE_ID);
CREATE INDEX IDX_MRCM_A_ID_V_ID ON MRCM_CONSTRAINTS (ATTRIBUTE_ID, VALUE_ID);

-- -----------------------------------------------------------------------------
-- REFERENCESET
-- 국제 및 애드온 패키지의 모든 Reference Set 통합 저장 테이블
-- FIELD1~FIELD7은 Reference Set 유형에 따라 의미가 다름:
--   Association Refset:  FIELD1=targetComponentId
--   Extended Map Refset: FIELD1=mapGroup, FIELD2=mapPriority, FIELD3=mapRule,
--                        FIELD4=mapAdvice, FIELD5=mapTarget, FIELD6=correlationId, FIELD7=mapCategoryId
--   Simple Map Refset:   FIELD1=mapTarget
-- MySQL UNIQUE KEY UUID → PostgreSQL UNIQUE 제약
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS REFERENCESET;
CREATE TABLE REFERENCESET (
    SEQ                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    -- UUID 형식의 Reference Set 멤버 고유 식별자 (36자)
    REFERENCESET_ID         CHAR(36)      NOT NULL,
    EFFECTIVE_TIME          CHAR(8)       NOT NULL,
    ACTIVE                  SMALLINT      NOT NULL,
    MODULE_ID               VARCHAR(18)   NOT NULL,
    REFSET_ID               VARCHAR(18)   NOT NULL,
    REFERENCED_COMPONENT_ID VARCHAR(18)   NOT NULL,
    FIELD1                  TEXT          DEFAULT NULL,
    FIELD2                  TEXT          DEFAULT NULL,
    FIELD3                  TEXT          DEFAULT NULL,
    FIELD4                  TEXT          DEFAULT NULL,
    -- FIELD5/FIELD6: MRCM ECL 표현식이 수만 자에 달하므로 VARCHAR 한계 초과 → TEXT
    FIELD5                  TEXT          DEFAULT NULL,
    FIELD6                  TEXT          DEFAULT NULL,
    FIELD7                  TEXT          DEFAULT NULL,
    DATE_CREATED            CHAR(8)       DEFAULT NULL,
    PRIMARY KEY (SEQ),
    -- RF2 멤버 UUID는 배포판 내에서 유일해야 함
    UNIQUE (REFERENCESET_ID)
);

CREATE INDEX IDX_REFERENCESET_ETIME_R_ID         ON REFERENCESET (EFFECTIVE_TIME, REFERENCESET_ID);
CREATE INDEX IDX_REFERENCESET_R_ID_R_C_ID         ON REFERENCESET (REFSET_ID, REFERENCED_COMPONENT_ID);
CREATE INDEX IDX_REFERENCESET_R_ID_R_C_ID_ETIME   ON REFERENCESET (REFSET_ID, REFERENCED_COMPONENT_ID, EFFECTIVE_TIME);
CREATE INDEX IDX_REFERENCESET_R_C_ID_R_ID_ETIME   ON REFERENCESET (REFERENCED_COMPONENT_ID, REFSET_ID, EFFECTIVE_TIME);

-- -----------------------------------------------------------------------------
-- USER_REFERENCESET
-- 사용자 정의 Reference Set 저장 테이블 (Concept/Description 편집기에서 생성)
-- INCLUDE_SUBTYPES: 1이면 하위 개념 포함 조회
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS USER_REFERENCESET;
CREATE TABLE USER_REFERENCESET (
    SEQ                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    REFERENCESET_ID         CHAR(36)      NOT NULL,
    EFFECTIVE_TIME          CHAR(8)       NOT NULL,
    ACTIVE                  SMALLINT      NOT NULL,
    MODULE_ID               VARCHAR(18)   NOT NULL,
    REFSET_ID               VARCHAR(18)   NOT NULL,
    REFERENCED_COMPONENT_ID VARCHAR(18)   NOT NULL,
    FIELD1                  VARCHAR(511)  DEFAULT NULL,
    FIELD2                  VARCHAR(255)  DEFAULT NULL,
    FIELD3                  VARCHAR(255)  DEFAULT NULL,
    FIELD4                  VARCHAR(255)  DEFAULT NULL,
    FIELD5                  VARCHAR(255)  DEFAULT NULL,
    FIELD6                  VARCHAR(255)  DEFAULT NULL,
    FIELD7                  VARCHAR(255)  DEFAULT NULL,
    DATE_CREATED            CHAR(8)       DEFAULT NULL,
    INCLUDE_SUBTYPES        SMALLINT      DEFAULT NULL,
    CONCEPT_ID              VARCHAR(18)   DEFAULT NULL,
    TYPE                    VARCHAR(45)   DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

-- -----------------------------------------------------------------------------
-- SCTID
-- SNOMED CT Extension ID 발급 이력 테이블 (Concept/Description 편집기 전용)
-- SEQ가 Extension item identifier로 직접 사용되므로 GENERATED BY DEFAULT 사용
-- CPNT_TYPE: 0=Concept, 1=Description, 2=Relationship (Partition Identifier)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS SCTID;
CREATE TABLE SCTID (
    SEQ         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CPNT_TYPE   INTEGER   NOT NULL,
    -- MySQL DEFAULT CURRENT_TIMESTAMP → PostgreSQL 동일하게 지원
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SEQ)
);

-- -----------------------------------------------------------------------------
-- TC (Transitive Closure / Hierarchy)
-- SNOMED CT IS-A 계층의 전이적 폐쇄(Transitive Closure) 테이블
-- TransitiveClosureGeneratorFromInferred.sh + TransitiveClosureGenerator.java 변환
--
-- 각 행은 IS-A 관계의 직접 부모-자식 쌍 하나를 나타낸다.
-- 다중 부모(multiple inheritance) 개념은 부모마다 별도 행으로 존재.
-- PATH: 루트(138875005)에서 PARENT_ID까지 '~' 구분 경로 (예: 138875005~A~B)
-- DEPTH: 루트 기준 깊이 (루트=0, 루트 직계자녀=1)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS TC;
CREATE TABLE TC (
    SEQ               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONCEPT_ID        VARCHAR(18)  NOT NULL,
    -- MySQL VARCHAR(255) → 512 (FSN은 255자 초과 가능)
    TERM              VARCHAR(512) NOT NULL,
    PARENT_ID         VARCHAR(18)  NOT NULL,
    CHILDREN_COUNT    INTEGER      DEFAULT 0,
    DESCENDANT_COUNT  INTEGER      DEFAULT 0,
    DEPTH             INTEGER      DEFAULT 0,
    -- MySQL VARCHAR(300) → TEXT (깊은 계층에서 경로 길이 초과 방지)
    PATH              TEXT         NOT NULL,
    DATE_CREATED      CHAR(8)      DEFAULT NULL,
    PRIMARY KEY (SEQ)
);

CREATE INDEX IDX_TC_C_ID ON TC (CONCEPT_ID);
CREATE INDEX IDX_TC_P_ID ON TC (PARENT_ID);
-- TEXT 컬럼은 직접 인덱스 불가 → 앞 300자에만 인덱스 (MySQL KEY IDX_TC_PATH 대응)
CREATE INDEX IDX_TC_PATH ON TC ((LEFT(PATH, 300)));

-- -----------------------------------------------------------------------------
-- SCHEME
-- 적재된 SNOMED CT 배포판 메타데이터 저장 테이블
-- AUTHORITY: 배포 기관 (예: SNOMED International)
-- DATE: 배포 기준일 (YYYYMMDD)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS SCHEME;
CREATE TABLE SCHEME (
    ID        VARCHAR(45) NOT NULL,
    NAME      VARCHAR(45) NOT NULL,
    EDITION   VARCHAR(45) NOT NULL,
    VERSION   VARCHAR(10) NOT NULL,
    AUTHORITY VARCHAR(45) NOT NULL,
    DATE      VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);
