# Dev configure

## OWL configure

owl.base.dir=/Users/dongwon/Downloads
owl.load.owlf=snomedct_owlf.owl

# Web socket
# please change with src/main/resources/logback.xml:configuration/property LOG_HOME value
ws.log.file=/Users/dongwon/Documents/project/termlogs


# SNOMED CT
sct.refset.dir=/Users/dongwon/tmp/snomedct/refset

# Elastic search
es.base.url=http://115.68.120.16:19210
es.base.username=ic_user
es.base.password=user!!

# Context Root
ctx.root=term